CREATE TABLE APP.MODULE_SETTINGS (
	NAMESPACE VARCHAR(255) NOT NULL,
	"SETTING_KEY" VARCHAR(100) NOT NULL,
	"SETTING_VALUE" VARCHAR(255),
	"SETTING_TYPE" VARCHAR(100) NOT NULL,
	"SETTING_ORDER" INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT MODULE_SETTINGS_PK PRIMARY KEY (NAMESPACE,"SETTING_KEY")
)